services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: read-me-api
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: node dist/infrastructure/fastify/server.js
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: pgvector/pgvector:pg17
    container_name: read-me-db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata: