services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: read-me
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    command: node dist/server/server.js
    restart: unless-stopped